version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - onlinenet

  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - onlinenet

networks:
  onlinenet:
    driver: bridge