# .NET 8.0 ile web uygulamasý imajý
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# .NET SDK imajý ile build iþlemi
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MextFullstackSaaS.WebApi/MextFullstackSaaS.WebApi.csproj", "MextFullstackSaaS.WebApi/"]
RUN dotnet restore "./MextFullstackSaaS.WebApi/MextFullstackSaaS.WebApi.csproj"
COPY . .
WORKDIR "/src/MextFullstackSaaS.WebApi"
RUN dotnet build "./MextFullstackSaaS.WebApi.csproj" -c Release -o /app/build

# Yayýnlama iþlemi
FROM build AS publish
RUN dotnet publish "./MextFullstackSaaS.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

# SQL Server imajýný ekle
FROM mcr.microsoft.com/mssql/server:2022-latest AS db
WORKDIR /db

# SQL Server için gerekli environment deðiþkenlerini ekle
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=YourStrong@Password
ENV MSSQL_PID=Express

EXPOSE 1433

# Web uygulamasý imajý ve SQL Server
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# SQL Server'ýn baþlatýlmasý
CMD /opt/mssql/bin/sqlservr & dotnet MextFullstackSaaS.WebApi.dll
